### ISSUE TITLE
DGPS

### ISSUE THREAD

**Issue by KipCrossing** [inmcm/micropyGPS#1]
Any chance of including a command to enable DGPS?

Cheers,

Kip

**Comment by inmcm** [comment]
I'm afraid I don't quite understand your request. Differential GPS (DGPS) is an improved form of GPS positioning involving multiple synchronized receivers. It cannot be enabled arbitrarily on any receiver.

More importantly, micropyGPS doesn't support issuing commands; it's really just a NMEA sentence paring engine. That's not to say it can't work with DGPS receivers, assuming they support the NMEA sentence standards. 

If there is a special DGPS NMEA sentence you want to parse, I can certainly look into accommodating that. Otherwise, you may want to look at my MTK command generator project if you need to issue a GPS control command in micropython.

**Comment by KipCrossing** [comment]
I've just given your code a test run and my mistake, I now realise its function. I'm using the same setup you have in the picture and the "Ultimate GPS" may be set to DGPS and returns a sentence such as "$PMTK001,313,3*31" to say its OK. However, I think this is a little outside the scope of your project. If you are interested in this particular function of the Ultimate GPS, see: http://forums.adafruit.com/viewtopic.php?f=19&t=28162#p177750

I might have a go at writing a script which can do what I want. It's my first time using UART so hopefully I can manage. Thanks for your project though, its quite helpful. 

EDIT: I just looked at your MTK project and its exactly what I need. Thank you so much.
